snowsql_config_path = "~/.snowsql/config"
snowsql_connection_name = "retail"

[default]
input_parameters = "()"
return_type = "string"
file = "app.zip"
name = "orders_update_sp"
handler = "app.main"
execute_as_caller = true

[dev]
database = "RETAIL"
schema = "HARMONIZED"
warehouse = "HOL_WH"
role = "RETAIL"
overwrite = true
