snowsql_config_path = "~/.snowsql/config"
snowsql_connection_name = "retail"

[default]
input_parameters = "(temp_f float)"
return_type = "float"
file = "app.zip"
name = "fahrenheit_to_celsius_udf"
handler = "app.main"
execute_as_caller = true

[dev]
database = "RETAIL"
schema = "ANALYTICS"
warehouse = "HOL_WH"
role = "RETAIL"
overwrite = true
